config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  
  get '/signup', to: 'users#new'
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end 
  end

  post 'microposts/share', to: 'microposts#share'
  post 'likes/show', to: 'likes#show'
  get 'likes/show', to: 'likes#show'
  
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  resources :likes, only: [:create, :destroy]

end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :likes

  default_scope -> { order(created_at: :desc) }

  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates :image, content_type: { in: %w[image/jpeg image/gif image/png], message: "must be a valid image format" },
                    size: { less_than: 5.megabytes, message: "should be less than 5MB." }

  # Returns a resized image for display.
  def display_image
    image.variant(resize_to_limit: [500, 500])
  end

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController

    before_action :logged_in_user, only: [:create, :destroy]
    before_action :correct_user, only: :destroy

    def create
        @micropost = current_user.microposts.build(micropost_params)
        @micropost.image.attach(params[:micropost][:image])
        if @micropost.save
            flash[:success] = "Micropost created!"
            redirect_to root_url
        else
            @feed_items = current_user.feed.paginate(page: params[:page])
            render 'static_pages/home'
        end
    end

    def destroy
        @micropost.destroy
        flash[:success] = "Micropost deleted"
        if request.referrer.nil? || request.referrer == microposts_url
            redirect_to root_url
        else
            redirect_to request.referrer
        end
        # redirect_back(fallback_location: root_url)
    end

    def share
        mp = Micropost.find(params[:id])
        content = mp.content
        @micropost = current_user.microposts.build(content: content)
        # @micropost.image.attach(mp.image) if mp.image 

        if @micropost.save
            flash[:success] = "Successfully shared the feed"
        else
            flash[:danger] = "Could not share the feed."
        end
        redirect_to root_url
    end

    private

        # def share_params
        #     params.require(:micropost).permit(:share_id)
        # end

        def micropost_params
            params.require(:micropost).permit(:content, :image)
        end 

        def correct_user
            @micropost = current_user.microposts.find_by(id: params[:id])
            redirect_to root_url if @micropost.nil? 
        end

end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
    <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
    <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
    <span class="content"><%= micropost.content %></span>
    <%= image_tag micropost.display_image if micropost.image.attached? %>

    <span class="timestamp">
        Posted <%= time_ago_in_words(micropost.created_at) %> ago.
        <% if current_user?(micropost.user) %>
            <%= link_to "delete", micropost, method: :delete, data: { confirm: "You sure?" } %>
        <% end %>
    </span> 

    <%= form_with(model: @likes, url: likes_show_url, local: true, class: "share") do |f| %>
            <%= hidden_field_tag :id, micropost.id %>
            <%= button_tag( :type => "submit" ) do %>
                <%= pluralize(micropost.likes.count, "Like") %>
            <% end %>
    <% end %>


    <% if !current_user?(micropost.user) %>
        <%= form_with(model: @micropost, url: microposts_share_path, local: true, class: "share") do |f| %>
            <%= hidden_field_tag :id, micropost.id %>
            <%= button_tag( :type => "submit" ) do %>
                <i class="fa-solid fa-share"></i>
            <% end %>
        <% end %>

        <%= form_with(model: @like, url: likes_url, local: false, class: "like") do |f| %>
            <%= hidden_field_tag :id, micropost.id %>
            <%= button_tag( :type => "submit" ) do %>

                <% if current_user.likes.find_by(micropost: micropost.id).nil? %>
                    <i class="fa-solid fa-heart"></i>
                <% else %>
                    <i class="fa-solid fa-heart red"></i>
                <% end %>
            <% end %>
        <% end %>

    <% end %>
    
        
</li>